Repository jenkinsci/macstadium-orka-plugin, pull requests merged in 2020-04, with the labels that each got.

#24 Include additional logging
  src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
  src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
  src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
  src/main/java/io/jenkins/plugins/orka/WaitSSHLauncher.java
  src/main/java/io/jenkins/plugins/orka/client/DeploymentResponse.java
  src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
Labels: chore, internal

#25 Hanlde failed deployments correctly
  src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
  src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
Labels: bug

#27 Correctly show the selected numCPUs value
  src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
  src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
  src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
  src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
Labels: bug

#26 Do not add cloud agents manually
  src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
Labels: chore

#28 Delete generated tokens for every API call
  src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
  src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
  src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
  src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
  src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
  src/main/java/io/jenkins/plugins/orka/helpers/ClientFactory.java
  src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
  src/test/java/io/jenkins/plugins/orka/ConfigNameCheckTest.java
  src/test/java/io/jenkins/plugins/orka/ImageItemsFillTest.java
  src/test/java/io/jenkins/plugins/orka/NodeItemsFillTest.java
  src/test/java/io/jenkins/plugins/orka/NodeNameCheckTest.java
  src/test/java/io/jenkins/plugins/orka/NodeResourcesCheckTest.java
  src/test/java/io/jenkins/plugins/orka/VMItemsFillTest.java
  src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java
Labels: bug
