Repository jenkinsci/macstadium-orka-plugin, pull requests merged in 2020-08, with the labels that each got.

#32 Increase Orka request timeout to 5 min
  src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
Labels: enhancement

#33 Update README with instance cap
  README.md
Labels: documentation

#34 (feat) Add config for ephemeral agents deployment timeout
  README.md
  src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
  src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
  src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
  src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
  src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
Labels: enhancement

#35 Make sure running instances are always a positive number
  src/main/java/io/jenkins/plugins/orka/helpers/CapacityHandler.java
  src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java
Labels: bug
